SELECT PR.PRODUCT_CODE, (PR.PRICE * SUM(OFF.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS PR
JOIN OFFLINE_SALE AS OFF
ON PR.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SALES DESC, PR.PRODUCT_CODE;
