SELECT i.ANIMAL_ID, i.NAME 
FROM ANIMAL_INS i 
JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID 
#WHERE o.datetime IS NOT NULL - NOT NDDED - BOTH DATETIMES IS NOT NULLABLE 
ORDER BY DATEDIFF(o.DATETIME,i.DATETIME) DESC 
LIMIT 2
