-- 자동차 종류가 세단, 또는 SUV인 차량 중에서 2022년 11월 1일부터 2022년 11월 30일까지 대여가 가능하고, 30일간의 대여 금액이 50 이상, 200 미만인 자동차에 대해서 ID, 종류, 대여 금액 리스트를 출력 
-- 대여 금액 기준 내림차순, 같을 경우 자동차 종류 오름차순 

-- 종류가 세단, SUV인 차량
# SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE IN ('세단', 'SUV')

-- 대여할 수 없는 차량 
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'

-- 30일 간 대여할 수 있는 차량 
# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '30%'

SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
    ROUND(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE ) / 100) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE ROUND(CAR.DAILY_FEE * 30 * (100-PLAN.DISCOUNT_RATE ) / 100 ) 
    BETWEEN 500000 AND 2000000
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
AND PLAN.DURATION_TYPE = '30일 이상'
AND CAR.CAR_TYPE IN ('SUV','세단')

ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_TYPE DESC;