SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
LEFT JOIN ANIMAL_INS AS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME NOT LIKE INS.SEX_UPON_INTAKE 
ORDER BY OUTS.ANIMAL_ID;