-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 
-- 2021년에 가입한 전체 회원들 중에서 상품을 구매한 회원수와 
-- 2021년에 가입한 회원 중 상품을 구매한 회원 / 2021년에 가입한 회원 수 
-- 년, 월 별로 출력하는 SQL문을 작성 
-- 비율은 소수점 두번째 자리에서 반올림, 전체 결과는 년을 기준으로 오름차순 

SELECT YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%' ),1) AS PURCHASED_RATIO
FROM USER_INFO AS A 
JOIN ONLINE_SALE AS B 
ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH




