-- 생산일자가 2022년 5월인 식품들의 식품ID, 식품이름, 총매출을 조회
-- 총매출 기준으로 내림차순, 식품ID를 기준으로 오름차순 

SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A 
RIGHT JOIN FOOD_ORDER AS B 
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID