-- 자동차 종류가 '트럭'인 자동차의 대여기록에 대해서 대여 금액을 구하여 대여 기록 ID와 대여 금액 리스트를 출력 
-- 대여 금액을 기준으로 내림차순, ID를 기준으로 내림차순 

SELECT A.HISTORY_ID,
       ROUND(B.DAILY_FEE * (DATEDIFF(A.END_DATE, A.START_DATE) + 1) * (100 - IFNULL(C.DISCOUNT_RATE, 0)) /
             100, 0) as FEE
FROM (SELECT *,
             CASE
                 WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
                 WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
                 WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
                 ELSE '90일 이상'
                 END DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ) AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B 
ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON C.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = C.DURATION_TYPE
WHERE B.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC