SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        
        UNION ALL
        
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
    ) AS COM
    GROUP BY FLAVOR
ORDER BY TOTAL DESC
    LIMIT 3)
    AS AASD
