-- 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하는 SQL문 

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A  
JOIN REST_REVIEW AS B 
ON A.MEMBER_ID = B.MEMBER_ID
JOIN (
    SELECT MEMBER_ID 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID 
    ORDER BY COUNT(*) DESC 
    LIMIT 1
) AS TopMembers
ON A.MEMBER_ID = TopMembers.MEMBER_ID
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT