-- 코드를 입력하세요
SELECT FIR.FLAVOR 
FROM FIRST_HALF AS FIR
JOIN ICECREAM_INFO AS INF
ON FIR.FLAVOR = INF.FLAVOR
WHERE FIR.TOTAL_ORDER > 3000 AND INF.INGREDIENT_TYPE LIKE 'fru%'
ORDER BY FIR.TOTAL_ORDER DESC