-- 자동차 종류가 '세단'인 자동차 중 10월에 대여를 시작한 기록이 있는 자동차ID
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID 
WHERE B.START_DATE LIKE '2022-10%' AND A.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC