-- 10월에 대여 기록이 있는 세단 종류의 자동차ID

SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS A 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B 
ON A.CAR_ID = B.CAR_ID
WHERE B.START_DATE LIKE '2022-10%' AND A.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC