-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_GRADE  AS C 
JOIN HR_EMPLOYEES  AS B
ON C.EMP_NO = B.EMP_NO
GROUP BY C.EMP_NO
ORDER BY SCORE DESC LIMIT 1;