-- 코드를 입력하세요
SELECT BOA.TITLE, BOA.BOARD_ID, REP.REPLY_ID, REP.WRITER_ID, REP.CONTENTS, DATE_FORMAT(REP.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE


FROM USED_GOODS_BOARD AS BOA 
JOIN USED_GOODS_REPLY AS REP
ON BOA.BOARD_ID = REP.BOARD_ID
WHERE BOA.CREATED_DATE LIKE '2022-10%'
ORDER BY REP.CREATED_DATE, BOA.TITLE